### ISSUE TITLE
样式优化

### ISSUE THREAD

**Issue by qianxiaofendou** [lvzhenbo/localStorage-manager#2]
1、表格(/src/components/Content.vue）里面(createColumns方法)输入框可以使用size="small"模式
2、表格的行高可以紧凑一点，这样一屏可以展示过多行，现在是四行，超过四行就需要滚动了
3、工具栏的按钮，也可以使用size="small"模式

以上，辛苦大大可以调整一下，感谢！

**Comment by lvzhenbo** [comment]
试试最新CI https://github.com/lvzhenbo/localStorage-manager/actions/runs/12046964250

**Comment by qianxiaofendou** [comment]
> 试试最新CI https://github.com/lvzhenbo/localStorage-manager/actions/runs/12046964250

刚试了一下，现在感觉舒服多了，视觉上感觉很舒服，一屏可以展示更多行了，感谢大佬！

再提个小小的建议：
1、工具栏的上下padding可以再小一点
2、表格和工具栏之间的间隙可以再小一点

**Comment by qianxiaofendou** [comment]
您的着这个项目是用的什么脚手架搭建的，可以安利一下么，或者有文章可以参考一下也可以，想学习一下！

**Comment by lvzhenbo** [comment]
一样，最新的CI。
用的东西你可以在package.json里看得到，不过这玩意目前半死不活，建议直接去用wxt.js，这玩意比我目前用的好，等wxt稳定了我也准备迁移过去

**Comment by qianxiaofendou** [comment]
> 一样，最新的CI。 用的东西你可以在package.json里看得到，不过这玩意目前半死不活，建议直接去用wxt.js，这玩意比我目前用的好，等wxt稳定了我也准备迁移过去

嗯嗯，我去看一下，感谢！！！

**Comment by lvzhenbo** [comment]
OK，已经提交谷歌商店审核了
